version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
        environment:
          - APP_DEBUG: true
          - APP_ENV: circleci
          - DB_CONNECTION: mysql
          - DB_DATABASE: laraec
          - DB_USERNAME: root
 
      - image: circleci/mysql:5.7.32-ram
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: true
          - MYSQL_DATABASE: laraec
 
    steps:
      - checkout
 
      - run: sudo apt update
      - run: sudo docker-php-ext-install pdo_mysql
 
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "htdocs/composer.json" }}
            - v1-dependencies-
 
      - run: 
          working_directory: htdocs
          command: composer install -n --prefer-dist
 
      - save_cache:
          key: v1-dependencies-{{ checksum "htdocs/composer.json" }}
          paths:
            - ./htdocs/vendor
 
      - run: 
          working_directory: htdocs
          command: echo "APP_KEY=" > .env.circleci
      - run: 
          working_directory: htdocs
          command: php artisan key:generate
      - run: 
          working_directory: htdocs
          command: php artisan migrate:refresh --seed --env=circleci
 
      - run: 
          working_directory: htdocs
          command: vendor/bin/phpunit --testdox

  deploy-prod:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: onamae.com deploy
          command: |
            curl -X POST -H "Content-Type: application/x-www-form-urlencoded" \
            --data-urlencode 'payload={"ref": "refs/heads/master"}'  \
            https://laraec.isystk.com/laravel-react-boilerplate/git-hook.php?key=Yfd3o8Jy5s

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy-prod:
          requires:
          - build
          filters:
            branches:
              only: master
